# Generated by Django 5.0.6 on 2024-06-28 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='poster',
        ),
    ]
